# This is a basic workflow that is manually triggered

name: Monthly Docker Hub Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
  - cron: "0 0 1 * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Web Request Action
      # You may pin to the exact commit or the version.
      # uses: Satak/webrequest-action@5fafb47657920704ad01cfb820fd9aacd81d74cf
      uses: Satak/webrequest-action@v1.2.3
      with:
        url: https://hub.docker.com/api/build/v1/source/38a89e4d-7cb2-4dbe-b6ae-5a12e6093a37/trigger/d5dfdba7-5dc5-45cc-a0dd-8d76bb1f7d34/call/
        method: POST
